# Generated by Django 3.1.2 on 2020-10-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0009_auto_20201030_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
